[build]
  functions = "public-functions"

[[redirects]]
  from = "/about/research-projects/"
  to = "/projects/current/"

[[redirects]]
  from = "/contact/"
  to = "/about/contact/"

[[redirects]]
  from = "/reports/"
  to = "/publications/"

[[redirects]]
  from = "/reports/*"
  to = "/publications/:splat"

[[redirects]]
  from = "/events/"
  to = "/"

[[redirects]]
  from = "/media/"
  to = "/about/research-projects/"

[[redirects]]
  from = "/media/related-research-projects/"
  to = "/about/research-partners/"

[[redirects]]
  from = "/about/network/"
  to = "/about/links/"

[[redirects]]
  from = "/media/resources/"
  to = "/"

[[redirects]]
  from = "/2017/*"
  to = "/"

[[redirects]]
  from = "/2018/*"
  to = "/"

[[redirects]]
  from = "/2019/*"
  to = "/"


[[redirects]]
  from = "/tools-resist/coping-strategies/"
  to = "/tools/coping-strategies/"

[[redirects]]
  from = "/tools-resist/"
  to = "/tools/coping-strategies/"

[[redirects]]
  from = "/tools/"
  to = "/tools/coping-strategies/"
  force = true

[[redirects]]
  from = "/tools-resist/participant-information-sheet/"
  to = "/tools/participant-information-sheet/"

[[redirects]]
  from = "/tools-resist/*"
  to = "/tools/coping-strategies/:splat"

[[redirects]]
  from = "/tools/maps-2"
  to = "/tools/maps"

[[redirects]]
  from = "/projects/trajects/"
  to = "/trajects/trajects-home/"

[[redirects]]
  from = "/projects/trajects/trajects-home/"
  to = "/trajects/trajects-home/"

[[redirects]]
  from = "/projects/trajects/jrs-2022/"
  to = "/trajects/jrs-2022/"

[[redirects]]
  from = "/projects/trajects/srs-2022/"
  to = "/trajects/srs-2022/"
